name: Publish signatures

on:
  push:
    branches: [main]
    paths:
      - 'SIGNATURES/**'

jobs:
  publish-signatures:
    permissions:
      contents: write
      packages: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v6
      - name: Install vendored dependencies
        run: |
          uvx mazette install

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish signatures
        run: |
          uv run ./ghcr-signer.py publish
