name: Verify signatures

on:
  pull_request:

jobs:
  verify-signatures:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8
      - uses: astral-sh/setup-uv@d0cc045d04ccac9d8b7881df0226f9e82c39688e
      - name: Install vendored dependencies
        run: |
          uvx mazette install
          ls -lah assets
      - name: Verify signatures
        run: |
          uv run ./ghcr-signer.py verify-local
